package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "categories")
public class Categories {

    /* ================= PRIMARY KEY ================= */

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /* ================= MANY-TO-ONE ================= */

    // parent category (self reference)
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_id")
    private Categories categoryParent;

    // company owning this category
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    private Companies companies;

    /* ================= BASIC COLUMN ================= */

    @Column(name = "name", length = 255)
    private String name;

    /* ================= ONE-TO-MANY ================= */

    // products under this category
    @OneToMany(mappedBy = "categories", fetch = FetchType.LAZY)
    private Set<Products> products = new HashSet<>();

    // child categories
    @OneToMany(mappedBy = "categoryParent", fetch = FetchType.LAZY)
    private Set<Categories> categoryChildren = new HashSet<>();

	public Categories() {
	}

	public Categories(Long id, Categories categoryParent, Companies companies, String name, Set<Products> products,
			Set<Categories> categoryChildren) {
		super();
		this.id = id;
		this.categoryParent = categoryParent;
		this.companies = companies;
		this.name = name;
		this.products = products;
		this.categoryChildren = categoryChildren;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Categories getCategories() {
		return categoryParent;
	}

	public void setCategories(Categories categories) {
		this.categoryParent = categories;
	}

	public Companies getCompanies() {
		return companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Products> getProductses() {
		return products;
	}

	public void setProductses(Set<Products> productses) {
		this.products = productses;
	}

	public Set<Categories> getCategorieses() {
		return categoryChildren;
	}

	public void setCategorieses(Set<Categories> categorieses) {
		this.categoryChildren = categorieses;
	}

	
}
