package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Companies generated by hbm2java
 */
@Entity
@Table(name = "companies")
public class Companies implements java.io.Serializable {

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /* ================= BASIC COLUMNS ================= */

    @Column(name = "company_code", length = 50)
    private String companyCode;

    @Column(name = "company_name", length = 255)
    private String companyName;

    @Column(name = "tax_code", length = 50)
    private String taxCode;

    @Column(name = "address", length = 255)
    private String address;

    @Column(name = "phone", length = 50)
    private String phone;

    @Column(name = "status")
    private Byte status;

    @Column(name = "created_at")
    private Timestamp createdAt;

    /* ================= RELATIONSHIPS ================= */
    /* All mapped by company_id in child tables */

    @OneToMany(mappedBy = "companies", fetch = FetchType.LAZY)
    private Set<Customers> customerses = new HashSet<>();

    @OneToMany(mappedBy = "companies", fetch = FetchType.LAZY)
    private Set<DeliveryOrders> deliveryOrderses = new HashSet<>();

    @OneToMany(mappedBy = "companies", fetch = FetchType.LAZY)
    private Set<Roles> roleses = new HashSet<>();

    @OneToMany(mappedBy = "companies", fetch = FetchType.LAZY)
    private Set<GoodsReceipts> goodsReceiptses = new HashSet<>();

    @OneToMany(mappedBy = "companies", fetch = FetchType.LAZY)
    private Set<DeliveryPartners> deliveryPartnerses = new HashSet<>();

    @OneToMany(mappedBy = "companies", fetch = FetchType.LAZY)
    private Set<Suppliers> supplierses = new HashSet<>();

    @OneToMany(mappedBy = "companies", fetch = FetchType.LAZY)
    private Set<InventoryLogs> inventoryLogses = new HashSet<>();

    @OneToMany(mappedBy = "companies", fetch = FetchType.LAZY)
    private Set<Warehouses> warehouseses = new HashSet<>();

    @OneToMany(mappedBy = "companies", fetch = FetchType.LAZY)
    private Set<Categories> categorieses = new HashSet<>();

    @OneToMany(mappedBy = "companies", fetch = FetchType.LAZY)
    private Set<Products> productses = new HashSet<>();

    @OneToMany(mappedBy = "companies", fetch = FetchType.LAZY)
    private Set<DeliveryLogs> deliveryLogses = new HashSet<>();

    @OneToMany(mappedBy = "companies", fetch = FetchType.LAZY)
    private Set<Users> userses = new HashSet<>();

    @OneToMany(mappedBy = "companies", fetch = FetchType.LAZY)
    private Set<Inventories> inventorieses = new HashSet<>();

    @OneToMany(mappedBy = "companies", fetch = FetchType.LAZY)
    private Set<Trucks> truckses = new HashSet<>();

    @OneToMany(mappedBy = "companies", fetch = FetchType.LAZY)
    private Set<GoodsIssues> goodsIssueses = new HashSet<>();

    @OneToMany(mappedBy = "companies", fetch = FetchType.LAZY)
    private Set<Drivers> driverses = new HashSet<>();

	public Companies() {
	}

	public Companies(Long id, String companyCode, String companyName, String taxCode, String address, String phone,
			Byte status, Timestamp createdAt, Set<Customers> customerses, Set<DeliveryOrders> deliveryOrderses,
			Set<Roles> roleses, Set<GoodsReceipts> goodsReceiptses, Set<DeliveryPartners> deliveryPartnerses,
			Set<Suppliers> supplierses, Set<InventoryLogs> inventoryLogses, Set<Warehouses> warehouseses,
			Set<Categories> categorieses, Set<Products> productses, Set<DeliveryLogs> deliveryLogses,
			Set<Users> userses, Set<Inventories> inventorieses, Set<Trucks> truckses, Set<GoodsIssues> goodsIssueses,
			Set<Drivers> driverses) {
		super();
		this.id = id;
		this.companyCode = companyCode;
		this.companyName = companyName;
		this.taxCode = taxCode;
		this.address = address;
		this.phone = phone;
		this.status = status;
		this.createdAt = createdAt;
		this.customerses = customerses;
		this.deliveryOrderses = deliveryOrderses;
		this.roleses = roleses;
		this.goodsReceiptses = goodsReceiptses;
		this.deliveryPartnerses = deliveryPartnerses;
		this.supplierses = supplierses;
		this.inventoryLogses = inventoryLogses;
		this.warehouseses = warehouseses;
		this.categorieses = categorieses;
		this.productses = productses;
		this.deliveryLogses = deliveryLogses;
		this.userses = userses;
		this.inventorieses = inventorieses;
		this.truckses = truckses;
		this.goodsIssueses = goodsIssueses;
		this.driverses = driverses;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCompanyCode() {
		return companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getTaxCode() {
		return taxCode;
	}

	public void setTaxCode(String taxCode) {
		this.taxCode = taxCode;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Byte getStatus() {
		return status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Timestamp getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Set<Customers> getCustomerses() {
		return customerses;
	}

	public void setCustomerses(Set<Customers> customerses) {
		this.customerses = customerses;
	}

	public Set<DeliveryOrders> getDeliveryOrderses() {
		return deliveryOrderses;
	}

	public void setDeliveryOrderses(Set<DeliveryOrders> deliveryOrderses) {
		this.deliveryOrderses = deliveryOrderses;
	}

	public Set<Roles> getRoleses() {
		return roleses;
	}

	public void setRoleses(Set<Roles> roleses) {
		this.roleses = roleses;
	}

	public Set<GoodsReceipts> getGoodsReceiptses() {
		return goodsReceiptses;
	}

	public void setGoodsReceiptses(Set<GoodsReceipts> goodsReceiptses) {
		this.goodsReceiptses = goodsReceiptses;
	}

	public Set<DeliveryPartners> getDeliveryPartnerses() {
		return deliveryPartnerses;
	}

	public void setDeliveryPartnerses(Set<DeliveryPartners> deliveryPartnerses) {
		this.deliveryPartnerses = deliveryPartnerses;
	}

	public Set<Suppliers> getSupplierses() {
		return supplierses;
	}

	public void setSupplierses(Set<Suppliers> supplierses) {
		this.supplierses = supplierses;
	}

	public Set<InventoryLogs> getInventoryLogses() {
		return inventoryLogses;
	}

	public void setInventoryLogses(Set<InventoryLogs> inventoryLogses) {
		this.inventoryLogses = inventoryLogses;
	}

	public Set<Warehouses> getWarehouseses() {
		return warehouseses;
	}

	public void setWarehouseses(Set<Warehouses> warehouseses) {
		this.warehouseses = warehouseses;
	}

	public Set<Categories> getCategorieses() {
		return categorieses;
	}

	public void setCategorieses(Set<Categories> categorieses) {
		this.categorieses = categorieses;
	}

	public Set<Products> getProductses() {
		return productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

	public Set<DeliveryLogs> getDeliveryLogses() {
		return deliveryLogses;
	}

	public void setDeliveryLogses(Set<DeliveryLogs> deliveryLogses) {
		this.deliveryLogses = deliveryLogses;
	}

	public Set<Users> getUserses() {
		return userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

	public Set<Inventories> getInventorieses() {
		return inventorieses;
	}

	public void setInventorieses(Set<Inventories> inventorieses) {
		this.inventorieses = inventorieses;
	}

	public Set<Trucks> getTruckses() {
		return truckses;
	}

	public void setTruckses(Set<Trucks> truckses) {
		this.truckses = truckses;
	}

	public Set<GoodsIssues> getGoodsIssueses() {
		return goodsIssueses;
	}

	public void setGoodsIssueses(Set<GoodsIssues> goodsIssueses) {
		this.goodsIssueses = goodsIssueses;
	}

	public Set<Drivers> getDriverses() {
		return driverses;
	}

	public void setDriverses(Set<Drivers> driverses) {
		this.driverses = driverses;
	}

	
	

}
