package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name = "customers")
public class Customers {

    /* ================= PRIMARY KEY ================= */

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /* ================= MANY-TO-ONE ================= */

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    private Companies companies;

    /* ================= BASIC COLUMNS ================= */

    @Column(name = "name", length = 255)
    private String name;

    @Column(name = "phone", length = 50)
    private String phone;

    @Column(name = "address", length = 255)
    private String address;

    /* ================= ONE-TO-MANY ================= */

    @OneToMany(mappedBy = "customers", fetch = FetchType.LAZY)
    private Set<GoodsIssues> goodsIssueses = new HashSet<>();

	public Customers() {
	}

	public Customers(Long id, Companies companies, String name, String phone, String address,
			Set<GoodsIssues> goodsIssueses) {
		super();
		this.id = id;
		this.companies = companies;
		this.name = name;
		this.phone = phone;
		this.address = address;
		this.goodsIssueses = goodsIssueses;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Companies getCompanies() {
		return companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Set<GoodsIssues> getGoodsIssueses() {
		return goodsIssueses;
	}

	public void setGoodsIssueses(Set<GoodsIssues> goodsIssueses) {
		this.goodsIssueses = goodsIssueses;
	}

	

}
