package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

import jakarta.persistence.*;

/**
 * DeliveryLogs generated by hbm2java
 */
@Entity
@Table(name = "delivery_logs")
public class DeliveryLogs {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // FK: delivery_order_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "delivery_order_id")
    private DeliveryOrders deliveryOrders;

    // FK: created_by → users.id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by")
    private Users users;

    // FK: company_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    private Companies companies;

    @Column(name = "event_time")
    private Timestamp eventTime;

    @Column(name = "event_code", length = 50)
    private String eventCode;

    @Column(name = "note", columnDefinition = "TEXT")
    private String note;

	public DeliveryLogs() {
	}

	public DeliveryLogs(DeliveryOrders deliveryOrders, Users users, Companies companies, Timestamp eventTime,
			String eventCode, String note) {
		this.deliveryOrders = deliveryOrders;
		this.users = users;
		this.companies = companies;
		this.eventTime = eventTime;
		this.eventCode = eventCode;
		this.note = note;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public DeliveryOrders getDeliveryOrders() {
		return this.deliveryOrders;
	}

	public void setDeliveryOrders(DeliveryOrders deliveryOrders) {
		this.deliveryOrders = deliveryOrders;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public Timestamp getEventTime() {
		return this.eventTime;
	}

	public void setEventTime(Timestamp eventTime) {
		this.eventTime = eventTime;
	}

	public String getEventCode() {
		return this.eventCode;
	}

	public void setEventCode(String eventCode) {
		this.eventCode = eventCode;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
