package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * DeliveryOrders generated by hbm2java
 */
@Entity
@Table(name = "delivery_orders")
public class DeliveryOrders {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // FK: goods_issue_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "goods_issue_id")
    private GoodsIssues goodsIssues;

    // FK: truck_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "truck_id")
    private Trucks trucks;

    // FK: driver_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "driver_id")
    private Drivers drivers;

    // FK: partner_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "partner_id")
    private DeliveryPartners deliveryPartners;

    // FK: company_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    private Companies companies;

    @Column(name = "tracking_code", length = 100)
    private String trackingCode;

    @Column(name = "delivery_address", length = 255)
    private String deliveryAddress;

    @Column(name = "delivery_phone", length = 50)
    private String deliveryPhone;

    @Column(name = "delivery_date")
    private Timestamp deliveryDate;

    @Column(name = "delivery_status")
    private Byte deliveryStatus;

    @Column(name = "cod_amount", precision = 18, scale = 2)
    private BigDecimal codAmount;

    @Column(name = "created_at")
    private Timestamp createdAt;

    // =====================
    // Inverse relationships
    // =====================

    @OneToMany(mappedBy = "deliveryOrders", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private Set<DeliveryItems> deliveryItemses = new HashSet<>();

    @OneToMany(mappedBy = "deliveryOrders", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private Set<DeliveryLogs> deliveryLogses = new HashSet<>();

	public DeliveryOrders() {
	}

	public DeliveryOrders(Long id, GoodsIssues goodsIssues, Trucks trucks, Drivers drivers,
			DeliveryPartners deliveryPartners, Companies companies, String trackingCode, String deliveryAddress,
			String deliveryPhone, Timestamp deliveryDate, Byte deliveryStatus, BigDecimal codAmount,
			Timestamp createdAt, Set<DeliveryItems> deliveryItemses, Set<DeliveryLogs> deliveryLogses) {
		super();
		this.id = id;
		this.goodsIssues = goodsIssues;
		this.trucks = trucks;
		this.drivers = drivers;
		this.deliveryPartners = deliveryPartners;
		this.companies = companies;
		this.trackingCode = trackingCode;
		this.deliveryAddress = deliveryAddress;
		this.deliveryPhone = deliveryPhone;
		this.deliveryDate = deliveryDate;
		this.deliveryStatus = deliveryStatus;
		this.codAmount = codAmount;
		this.createdAt = createdAt;
		this.deliveryItemses = deliveryItemses;
		this.deliveryLogses = deliveryLogses;
	}



	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public GoodsIssues getGoodsIssues() {
		return this.goodsIssues;
	}

	public void setGoodsIssues(GoodsIssues goodsIssues) {
		this.goodsIssues = goodsIssues;
	}

	public Trucks getTrucks() {
		return this.trucks;
	}

	public void setTrucks(Trucks trucks) {
		this.trucks = trucks;
	}

	public Drivers getDrivers() {
		return this.drivers;
	}

	public void setDrivers(Drivers drivers) {
		this.drivers = drivers;
	}

	public DeliveryPartners getDeliveryPartners() {
		return this.deliveryPartners;
	}

	public void setDeliveryPartners(DeliveryPartners deliveryPartners) {
		this.deliveryPartners = deliveryPartners;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getTrackingCode() {
		return this.trackingCode;
	}

	public void setTrackingCode(String trackingCode) {
		this.trackingCode = trackingCode;
	}

	public String getDeliveryAddress() {
		return this.deliveryAddress;
	}

	public void setDeliveryAddress(String deliveryAddress) {
		this.deliveryAddress = deliveryAddress;
	}

	public String getDeliveryPhone() {
		return this.deliveryPhone;
	}

	public void setDeliveryPhone(String deliveryPhone) {
		this.deliveryPhone = deliveryPhone;
	}

	public Timestamp getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Timestamp deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public Byte getDeliveryStatus() {
		return this.deliveryStatus;
	}

	public void setDeliveryStatus(Byte deliveryStatus) {
		this.deliveryStatus = deliveryStatus;
	}

	public BigDecimal getCodAmount() {
		return this.codAmount;
	}

	public void setCodAmount(BigDecimal codAmount) {
		this.codAmount = codAmount;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Set<DeliveryItems> getDeliveryItemses() {
		return deliveryItemses;
	}

	public void setDeliveryItemses(Set<DeliveryItems> deliveryItemses) {
		this.deliveryItemses = deliveryItemses;
	}

	public Set<DeliveryLogs> getDeliveryLogses() {
		return deliveryLogses;
	}

	public void setDeliveryLogses(Set<DeliveryLogs> deliveryLogses) {
		this.deliveryLogses = deliveryLogses;
	}

	

}
