package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * DeliveryPartners generated by hbm2java
 */
@Entity
@Table(name = "delivery_partners")
public class DeliveryPartners {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // FK: company_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    private Companies companies;

    @Column(name = "partner_code", length = 50)
    private String partnerCode;

    @Column(name = "partner_name", length = 255)
    private String partnerName;

    @Column(name = "supports_cod")
    private Byte supportsCod;

    /**
     * MySQL JSON column
     * You can later improve this using:
     *  - @Convert
     *  - or Hibernate Types (JsonType)
     */
    @Column(name = "api_config", columnDefinition = "json")
    private String apiConfig;

    @Column(name = "status")
    private Byte status;

    @Column(name = "created_at")
    private Timestamp createdAt;

    // =====================
    // Inverse relationship
    // =====================

    @OneToMany(mappedBy = "deliveryPartners", fetch = FetchType.LAZY)
    private Set<DeliveryOrders> deliveryOrderses = new HashSet<>();

	public DeliveryPartners() {
	}


	public DeliveryPartners(Long id, Companies companies, String partnerCode, String partnerName, Byte supportsCod,
			String apiConfig, Byte status, Timestamp createdAt, Set<DeliveryOrders> deliveryOrderses) {
		super();
		this.id = id;
		this.companies = companies;
		this.partnerCode = partnerCode;
		this.partnerName = partnerName;
		this.supportsCod = supportsCod;
		this.apiConfig = apiConfig;
		this.status = status;
		this.createdAt = createdAt;
		this.deliveryOrderses = deliveryOrderses;
	}



	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getPartnerCode() {
		return this.partnerCode;
	}

	public void setPartnerCode(String partnerCode) {
		this.partnerCode = partnerCode;
	}

	public String getPartnerName() {
		return this.partnerName;
	}

	public void setPartnerName(String partnerName) {
		this.partnerName = partnerName;
	}

	public Byte getSupportsCod() {
		return this.supportsCod;
	}

	public void setSupportsCod(Byte supportsCod) {
		this.supportsCod = supportsCod;
	}

	public String getApiConfig() {
		return this.apiConfig;
	}

	public void setApiConfig(String apiConfig) {
		this.apiConfig = apiConfig;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}


	public Set<DeliveryOrders> getDeliveryOrderses() {
		return deliveryOrderses;
	}


	public void setDeliveryOrderses(Set<DeliveryOrders> deliveryOrderses) {
		this.deliveryOrderses = deliveryOrderses;
	}



}
