package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Drivers generated by hbm2java
 */
@Entity
@Table(name = "drivers")
public class Drivers {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // FK: truck_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "truck_id")
    private Trucks trucks;

    // FK: company_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    private Companies companies;

    @Column(name = "full_name", length = 255)
    private String fullName;

    @Column(name = "phone", length = 50)
    private String phone;

    @Column(name = "status")
    private Byte status;

    @Column(name = "created_at")
    private Timestamp createdAt;

    // =====================
    // Inverse relationship
    // =====================

    @OneToMany(mappedBy = "drivers", fetch = FetchType.LAZY)
    private Set<DeliveryOrders> deliveryOrderses = new HashSet<>();

	public Drivers() {
	}


	public Drivers(Long id, Trucks trucks, Companies companies, String fullName, String phone, Byte status,
			Timestamp createdAt, Set<DeliveryOrders> deliveryOrderses) {
		super();
		this.id = id;
		this.trucks = trucks;
		this.companies = companies;
		this.fullName = fullName;
		this.phone = phone;
		this.status = status;
		this.createdAt = createdAt;
		this.deliveryOrderses = deliveryOrderses;
	}


	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Trucks getTrucks() {
		return this.trucks;
	}

	public void setTrucks(Trucks trucks) {
		this.trucks = trucks;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}


	public Set<DeliveryOrders> getDeliveryOrderses() {
		return deliveryOrderses;
	}


	public void setDeliveryOrderses(Set<DeliveryOrders> deliveryOrderses) {
		this.deliveryOrderses = deliveryOrderses;
	}



}
