package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * GoodsIssues generated by hbm2java
 */
@Entity
@Table(name = "goods_issues")
public class GoodsIssues {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /* =====================
       Relationships (ManyToOne)
       ===================== */

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "truck_id")
    private Trucks trucks;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "warehouse_id")
    private Warehouses warehouses;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id")
    private Customers customers;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by")
    private Users users;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    private Companies companies;

    /* =====================
       Columns
       ===================== */

    @Column(name = "issue_no", length = 100)
    private String issueNo;

    @Column(name = "created_at")
    private Timestamp createdAt;

    @Column(name = "status")
    private Byte status;

    @Column(name = "delivery_order_id")
    private Long deliveryOrderId;

    @Column(name = "delivery_status")
    private Byte deliveryStatus;

    /* =====================
       Relationships (OneToMany)
       ===================== */

    @OneToMany(mappedBy = "goodsIssues", fetch = FetchType.LAZY)
    private Set<DeliveryOrders> deliveryOrderses = new HashSet<>();

    @OneToMany(mappedBy = "goodsIssues", fetch = FetchType.LAZY)
    private Set<GoodsIssueItems> goodsIssueItemses = new HashSet<>();

	public GoodsIssues() {
	}


	public GoodsIssues(Long id, Trucks trucks, Warehouses warehouses, Customers customers, Users users,
			Companies companies, String issueNo, Timestamp createdAt, Byte status, Long deliveryOrderId,
			Byte deliveryStatus, Set<DeliveryOrders> deliveryOrderses, Set<GoodsIssueItems> goodsIssueItemses) {
		super();
		this.id = id;
		this.trucks = trucks;
		this.warehouses = warehouses;
		this.customers = customers;
		this.users = users;
		this.companies = companies;
		this.issueNo = issueNo;
		this.createdAt = createdAt;
		this.status = status;
		this.deliveryOrderId = deliveryOrderId;
		this.deliveryStatus = deliveryStatus;
		this.deliveryOrderses = deliveryOrderses;
		this.goodsIssueItemses = goodsIssueItemses;
	}



	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Trucks getTrucks() {
		return this.trucks;
	}

	public void setTrucks(Trucks trucks) {
		this.trucks = trucks;
	}

	public Warehouses getWarehouses() {
		return this.warehouses;
	}

	public void setWarehouses(Warehouses warehouses) {
		this.warehouses = warehouses;
	}

	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getIssueNo() {
		return this.issueNo;
	}

	public void setIssueNo(String issueNo) {
		this.issueNo = issueNo;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Long getDeliveryOrderId() {
		return this.deliveryOrderId;
	}

	public void setDeliveryOrderId(Long deliveryOrderId) {
		this.deliveryOrderId = deliveryOrderId;
	}

	public Byte getDeliveryStatus() {
		return this.deliveryStatus;
	}

	public void setDeliveryStatus(Byte deliveryStatus) {
		this.deliveryStatus = deliveryStatus;
	}


	public Set<DeliveryOrders> getDeliveryOrderses() {
		return deliveryOrderses;
	}


	public void setDeliveryOrderses(Set<DeliveryOrders> deliveryOrderses) {
		this.deliveryOrderses = deliveryOrderses;
	}


	public Set<GoodsIssueItems> getGoodsIssueItemses() {
		return goodsIssueItemses;
	}


	public void setGoodsIssueItemses(Set<GoodsIssueItems> goodsIssueItemses) {
		this.goodsIssueItemses = goodsIssueItemses;
	}

	

}
