package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;

import jakarta.persistence.*;

/**
 * GoodsReceiptItems generated by hbm2java
 */
@Entity
@Table(name = "goods_receipt_items")
public class GoodsReceiptItems {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // FK: receipt_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "receipt_id")
    private GoodsReceipts goodsReceipts;

    // FK: product_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id")
    private Products products;

    @Column(name = "quantity")
    private Integer quantity;

    @Column(name = "unit_price", precision = 18, scale = 2)
    private BigDecimal unitPrice;

	public GoodsReceiptItems() {
	}

	public GoodsReceiptItems(Products products, GoodsReceipts goodsReceipts, Integer quantity, BigDecimal unitPrice) {
		this.products = products;
		this.goodsReceipts = goodsReceipts;
		this.quantity = quantity;
		this.unitPrice = unitPrice;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public GoodsReceipts getGoodsReceipts() {
		return this.goodsReceipts;
	}

	public void setGoodsReceipts(GoodsReceipts goodsReceipts) {
		this.goodsReceipts = goodsReceipts;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

}
