package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * GoodsReceipts generated by hbm2java
 */
@Entity
@Table(name = "goods_receipts")
public class GoodsReceipts {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // FK: supplier_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "supplier_id")
    private Suppliers suppliers;

    // FK: warehouse_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "warehouse_id")
    private Warehouses warehouses;

    // FK: created_by
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by")
    private Users users;

    // FK: company_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    private Companies companies;

    @Column(name = "receipt_no", length = 100)
    private String receiptNo;

    @Column(name = "created_at")
    private Timestamp createdAt;

    @Column(name = "status")
    private Byte status;

    // One receipt → many items
    @OneToMany(mappedBy = "goodsReceipts", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private Set<GoodsReceiptItems> goodsReceiptItemses = new HashSet<>();

	public GoodsReceipts() {
	}

	public GoodsReceipts(Suppliers suppliers, Warehouses warehouses, Users users, Companies companies, String receiptNo,
			Timestamp createdAt, Byte status, Set goodsReceiptItemses) {
		this.suppliers = suppliers;
		this.warehouses = warehouses;
		this.users = users;
		this.companies = companies;
		this.receiptNo = receiptNo;
		this.createdAt = createdAt;
		this.status = status;
		this.goodsReceiptItemses = goodsReceiptItemses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Suppliers getSuppliers() {
		return this.suppliers;
	}

	public void setSuppliers(Suppliers suppliers) {
		this.suppliers = suppliers;
	}

	public Warehouses getWarehouses() {
		return this.warehouses;
	}

	public void setWarehouses(Warehouses warehouses) {
		this.warehouses = warehouses;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getReceiptNo() {
		return this.receiptNo;
	}

	public void setReceiptNo(String receiptNo) {
		this.receiptNo = receiptNo;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Set getGoodsReceiptItemses() {
		return this.goodsReceiptItemses;
	}

	public void setGoodsReceiptItemses(Set goodsReceiptItemses) {
		this.goodsReceiptItemses = goodsReceiptItemses;
	}

}
