package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;

import jakarta.persistence.*;

/**
 * GoodsIssueItems generated by hbm2java
 */
@Entity
@Table(name = "goods_issue_items")
public class GoodsIssueItems {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // FK: issue_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "issue_id")
    private GoodsIssues goodsIssues;

    // FK: product_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id")
    private Products products;

    @Column(name = "quantity")
    private Integer quantity;

    @Column(name = "unit_price", precision = 18, scale = 2)
    private BigDecimal unitPrice;

	public GoodsIssueItems() {
	}

	public GoodsIssueItems(GoodsIssues goodsIssues, Products products, Integer quantity, BigDecimal unitPrice) {
		this.goodsIssues = goodsIssues;
		this.products = products;
		this.quantity = quantity;
		this.unitPrice = unitPrice;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public GoodsIssues getGoodsIssues() {
		return this.goodsIssues;
	}

	public void setGoodsIssues(GoodsIssues goodsIssues) {
		this.goodsIssues = goodsIssues;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

}
