package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

import jakarta.persistence.*;

/**
 * Inventories generated by hbm2java
 */
@Entity
@Table(name = "inventories")
public class Inventories {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // FK: location_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "location_id")
    private WarehouseLocations warehouseLocations;

    // FK: product_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id")
    private Products products;

    // FK: warehouse_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "warehouse_id")
    private Warehouses warehouses;

    // FK: company_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    private Companies companies;

    @Column(name = "quantity")
    private Integer quantity;

    @Column(name = "last_updated")
    private Timestamp lastUpdated;

	public Inventories() {
	}

	public Inventories(WarehouseLocations warehouseLocations, Products products, Warehouses warehouses,
			Companies companies, Integer quantity, Timestamp lastUpdated) {
		this.warehouseLocations = warehouseLocations;
		this.products = products;
		this.warehouses = warehouses;
		this.companies = companies;
		this.quantity = quantity;
		this.lastUpdated = lastUpdated;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public WarehouseLocations getWarehouseLocations() {
		return this.warehouseLocations;
	}

	public void setWarehouseLocations(WarehouseLocations warehouseLocations) {
		this.warehouseLocations = warehouseLocations;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Warehouses getWarehouses() {
		return this.warehouses;
	}

	public void setWarehouses(Warehouses warehouses) {
		this.warehouses = warehouses;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Timestamp getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Timestamp lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
