package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Permissions generated by hbm2java
 */
@Entity
@Table(name = "permissions")
public class Permissions {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "permission_code", length = 100)
    private String permissionCode;

    @Column(name = "description", length = 255)
    private String description;

    // Many-to-Many with Roles
    @ManyToMany(mappedBy = "permissions", fetch = FetchType.LAZY)
    private Set<Roles> roleses = new HashSet<>();

	public Permissions() {
	}


	public Permissions(Long id, String permissionCode, String description, Set<Roles> roleses) {
		super();
		this.id = id;
		this.permissionCode = permissionCode;
		this.description = description;
		this.roleses = roleses;
	}



	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPermissionCode() {
		return this.permissionCode;
	}

	public void setPermissionCode(String permissionCode) {
		this.permissionCode = permissionCode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Roles> getRoleses() {
		return roleses;
	}

	public void setRoleses(Set<Roles> roleses) {
		this.roleses = roleses;
	}

	

}
