package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products")
public class Products {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ---------- Many-to-One ----------
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    private Categories categories;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "unit_id")
    private Units units;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    private Companies companies;

    // ---------- Basic fields ----------
    @Column(name = "sku", length = 100)
    private String sku;

    @Column(name = "barcode", length = 100)
    private String barcode;

    @Column(name = "name", length = 255)
    private String name;

    @Column(name = "cost_price", precision = 15, scale = 2)
    private BigDecimal costPrice;

    @Column(name = "sale_price", precision = 15, scale = 2)
    private BigDecimal salePrice;

    @Column(name = "status")
    private Byte status;

    // ---------- One-to-Many ----------
    @OneToMany(mappedBy = "products", fetch = FetchType.LAZY)
    private Set<GoodsReceiptItems> goodsReceiptItemses = new HashSet<>();

    @OneToMany(mappedBy = "products", fetch = FetchType.LAZY)
    private Set<GoodsIssueItems> goodsIssueItemses = new HashSet<>();

    @OneToMany(mappedBy = "products", fetch = FetchType.LAZY)
    private Set<Inventories> inventorieses = new HashSet<>();

    @OneToMany(mappedBy = "products", fetch = FetchType.LAZY)
    private Set<InventoryLogs> inventoryLogses = new HashSet<>();

    @OneToMany(mappedBy = "products", fetch = FetchType.LAZY)
    private Set<DeliveryItems> deliveryItemses = new HashSet<>();

	public Products() {
	}


	public Products(Long id, Categories categories, Units units, Companies companies, String sku, String barcode,
			String name, BigDecimal costPrice, BigDecimal salePrice, Byte status,
			Set<GoodsReceiptItems> goodsReceiptItemses, Set<GoodsIssueItems> goodsIssueItemses,
			Set<Inventories> inventorieses, Set<InventoryLogs> inventoryLogses, Set<DeliveryItems> deliveryItemses) {
		super();
		this.id = id;
		this.categories = categories;
		this.units = units;
		this.companies = companies;
		this.sku = sku;
		this.barcode = barcode;
		this.name = name;
		this.costPrice = costPrice;
		this.salePrice = salePrice;
		this.status = status;
		this.goodsReceiptItemses = goodsReceiptItemses;
		this.goodsIssueItemses = goodsIssueItemses;
		this.inventorieses = inventorieses;
		this.inventoryLogses = inventoryLogses;
		this.deliveryItemses = deliveryItemses;
	}



	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	public Units getUnits() {
		return this.units;
	}

	public void setUnits(Units units) {
		this.units = units;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(BigDecimal costPrice) {
		this.costPrice = costPrice;
	}

	public BigDecimal getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(BigDecimal salePrice) {
		this.salePrice = salePrice;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}


	public Set<GoodsReceiptItems> getGoodsReceiptItemses() {
		return goodsReceiptItemses;
	}


	public void setGoodsReceiptItemses(Set<GoodsReceiptItems> goodsReceiptItemses) {
		this.goodsReceiptItemses = goodsReceiptItemses;
	}


	public Set<GoodsIssueItems> getGoodsIssueItemses() {
		return goodsIssueItemses;
	}


	public void setGoodsIssueItemses(Set<GoodsIssueItems> goodsIssueItemses) {
		this.goodsIssueItemses = goodsIssueItemses;
	}


	public Set<Inventories> getInventorieses() {
		return inventorieses;
	}


	public void setInventorieses(Set<Inventories> inventorieses) {
		this.inventorieses = inventorieses;
	}


	public Set<InventoryLogs> getInventoryLogses() {
		return inventoryLogses;
	}


	public void setInventoryLogses(Set<InventoryLogs> inventoryLogses) {
		this.inventoryLogses = inventoryLogses;
	}


	public Set<DeliveryItems> getDeliveryItemses() {
		return deliveryItemses;
	}


	public void setDeliveryItemses(Set<DeliveryItems> deliveryItemses) {
		this.deliveryItemses = deliveryItemses;
	}


}
