package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles")
public class Roles {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ---------- Many-to-One ----------
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    private Companies companies;

    // ---------- Basic fields ----------
    @Column(name = "role_name", length = 100, nullable = false)
    private String roleName;

    // ---------- One-to-Many ----------
    @OneToMany(mappedBy = "roles", fetch = FetchType.LAZY)
    private Set<Users> userses = new HashSet<>();

    // ---------- Many-to-Many ----------
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
        name = "roles_permissions",
        joinColumns = @JoinColumn(name = "role_id"),
        inverseJoinColumns = @JoinColumn(name = "permission_id")
    )
    private Set<Permissions> permissions = new HashSet<>();

	public Roles() {
	}

	

	public Roles(Long id, Companies companies, String roleName, Set<Users> userses, Set<Permissions> permissions) {
		super();
		this.id = id;
		this.companies = companies;
		this.roleName = roleName;
		this.userses = userses;
		this.permissions = permissions;
	}


	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}


	public Set<Users> getUserses() {
		return userses;
	}


	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}


	public Set<Permissions> getPermissionses() {
		return permissions;
	}


	public void setPermissionses(Set<Permissions> permissionses) {
		this.permissions = permissionses;
	}


}
