package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Suppliers generated by hbm2java
 */
@Entity
@Table(name = "suppliers")
public class Suppliers {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ---------- Many-to-One ----------
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    private Companies companies;

    // ---------- Basic fields ----------
    @Column(name = "name", length = 255, nullable = false)
    private String name;

    @Column(name = "phone", length = 50)
    private String phone;

    @Column(name = "address", length = 255)
    private String address;

    // ---------- One-to-Many ----------
    @OneToMany(mappedBy = "suppliers", fetch = FetchType.LAZY)
    private Set<GoodsReceipts> goodsReceiptses = new HashSet<>();


	public Suppliers() {
	}


	public Suppliers(Long id, Companies companies, String name, String phone, String address,
			Set<GoodsReceipts> goodsReceiptses) {
		super();
		this.id = id;
		this.companies = companies;
		this.name = name;
		this.phone = phone;
		this.address = address;
		this.goodsReceiptses = goodsReceiptses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Set<GoodsReceipts> getGoodsReceiptses() {
		return goodsReceiptses;
	}

	public void setGoodsReceiptses(Set<GoodsReceipts> goodsReceiptses) {
		this.goodsReceiptses = goodsReceiptses;
	}


}
