package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Trucks generated by hbm2java
 */
@Entity
@Table(name = "trucks")
public class Trucks {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ---------- Many-to-One ----------
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    private Companies companies;

    // ---------- Basic fields ----------
    @Column(name = "license_plate", length = 50)
    private String licensePlate;

    @Column(name = "truck_type", length = 50)
    private String truckType;

    @Column(name = "capacity_kg")
    private Integer capacityKg;

    @Column(name = "status")
    private Byte status;

    @Column(name = "created_at")
    private Timestamp createdAt;

    // ---------- One-to-Many ----------
    @OneToMany(mappedBy = "trucks", fetch = FetchType.LAZY)
    private Set<DeliveryOrders> deliveryOrderses = new HashSet<>();

    @OneToMany(mappedBy = "trucks", fetch = FetchType.LAZY)
    private Set<Drivers> driverses = new HashSet<>();

    @OneToMany(mappedBy = "trucks", fetch = FetchType.LAZY)
    private Set<GoodsIssues> goodsIssueses = new HashSet<>();

	public Trucks() {
	}

	public Trucks(Long id, Companies companies, String licensePlate, String truckType, Integer capacityKg, Byte status,
			Timestamp createdAt, Set<DeliveryOrders> deliveryOrderses, Set<Drivers> driverses,
			Set<GoodsIssues> goodsIssueses) {
		super();
		this.id = id;
		this.companies = companies;
		this.licensePlate = licensePlate;
		this.truckType = truckType;
		this.capacityKg = capacityKg;
		this.status = status;
		this.createdAt = createdAt;
		this.deliveryOrderses = deliveryOrderses;
		this.driverses = driverses;
		this.goodsIssueses = goodsIssueses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getLicensePlate() {
		return this.licensePlate;
	}

	public void setLicensePlate(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	public String getTruckType() {
		return this.truckType;
	}

	public void setTruckType(String truckType) {
		this.truckType = truckType;
	}

	public Integer getCapacityKg() {
		return this.capacityKg;
	}

	public void setCapacityKg(Integer capacityKg) {
		this.capacityKg = capacityKg;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Set<DeliveryOrders> getDeliveryOrderses() {
		return deliveryOrderses;
	}

	public void setDeliveryOrderses(Set<DeliveryOrders> deliveryOrderses) {
		this.deliveryOrderses = deliveryOrderses;
	}

	public Set<Drivers> getDriverses() {
		return driverses;
	}

	public void setDriverses(Set<Drivers> driverses) {
		this.driverses = driverses;
	}

	public Set<GoodsIssues> getGoodsIssueses() {
		return goodsIssueses;
	}

	public void setGoodsIssueses(Set<GoodsIssues> goodsIssueses) {
		this.goodsIssueses = goodsIssueses;
	}

}
