package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Units generated by hbm2java
 */
@Entity
@Table(name = "units")
public class Units {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "unit_name", length = 50)
    private String unitName;

    @OneToMany(mappedBy = "units", fetch = FetchType.LAZY)
    private Set<Products> productses = new HashSet<>();

	public Units() {
	}


	public Units(Long id, String unitName, Set<Products> productses) {
		super();
		this.id = id;
		this.unitName = unitName;
		this.productses = productses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUnitName() {
		return this.unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}


	public Set<Products> getProductses() {
		return productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}


}
