package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.annotations.CreationTimestamp;

import jakarta.persistence.*;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users")
public class Users {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /* =====================
       Relationships
       ===================== */

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "role_id")
    private Roles roles;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    private Companies companies;

    /* =====================
       Columns
       ===================== */

    @Column(name = "username", length = 100)
    private String username;

    @Column(name = "password_hash", length = 255)
    private String passwordHash;

    @Column(name = "full_name", length = 255)
    private String fullName;

    @Column(name = "status")
    private Byte status;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private Timestamp createdAt;

    /* =====================
       One-to-many mappings
       ===================== */

    @OneToMany(mappedBy = "users", fetch = FetchType.LAZY)
    private Set<DeliveryLogs> deliveryLogses = new HashSet<>();

    @OneToMany(mappedBy = "users", fetch = FetchType.LAZY)
    private Set<GoodsIssues> goodsIssueses = new HashSet<>();

    @OneToMany(mappedBy = "users", fetch = FetchType.LAZY)
    private Set<GoodsReceipts> goodsReceiptses = new HashSet<>();

	public Users() {
	}

	public Users(Long id, Roles roles, Companies companies, String username, String passwordHash, String fullName,
			Byte status, Timestamp createdAt, Set<DeliveryLogs> deliveryLogses, Set<GoodsIssues> goodsIssueses,
			Set<GoodsReceipts> goodsReceiptses) {
		super();
		this.id = id;
		this.roles = roles;
		this.companies = companies;
		this.username = username;
		this.passwordHash = passwordHash;
		this.fullName = fullName;
		this.status = status;
		this.createdAt = createdAt;
		this.deliveryLogses = deliveryLogses;
		this.goodsIssueses = goodsIssueses;
		this.goodsReceiptses = goodsReceiptses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPasswordHash() {
		return this.passwordHash;
	}

	public void setPasswordHash(String passwordHash) {
		this.passwordHash = passwordHash;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Set<DeliveryLogs> getDeliveryLogses() {
		return deliveryLogses;
	}

	public void setDeliveryLogses(Set<DeliveryLogs> deliveryLogses) {
		this.deliveryLogses = deliveryLogses;
	}

	public Set<GoodsIssues> getGoodsIssueses() {
		return goodsIssueses;
	}

	public void setGoodsIssueses(Set<GoodsIssues> goodsIssueses) {
		this.goodsIssueses = goodsIssueses;
	}

	public Set<GoodsReceipts> getGoodsReceiptses() {
		return goodsReceiptses;
	}

	public void setGoodsReceiptses(Set<GoodsReceipts> goodsReceiptses) {
		this.goodsReceiptses = goodsReceiptses;
	}


}
