package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Warehouses generated by hbm2java
 */
@Entity
@Table(name = "warehouses")
public class Warehouses {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /* =====================
       Relationships
       ===================== */

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    private Companies companies;

    @OneToMany(mappedBy = "warehouses", fetch = FetchType.LAZY)
    private Set<GoodsReceipts> goodsReceiptses = new HashSet<>();

    @OneToMany(mappedBy = "warehouses", fetch = FetchType.LAZY)
    private Set<GoodsIssues> goodsIssueses = new HashSet<>();

    @OneToMany(mappedBy = "warehouses", fetch = FetchType.LAZY)
    private Set<Inventories> inventorieses = new HashSet<>();

    @OneToMany(mappedBy = "warehouses", fetch = FetchType.LAZY)
    private Set<InventoryLogs> inventoryLogses = new HashSet<>();

    @OneToMany(mappedBy = "warehouses", fetch = FetchType.LAZY)
    private Set<WarehouseLocations> warehouseLocationses = new HashSet<>();

    /* =====================
       Columns
       ===================== */

    @Column(name = "code", length = 50)
    private String code;

    @Column(name = "name", length = 255)
    private String name;

    @Column(name = "address", length = 255)
    private String address;

    @Column(name = "status")
    private Byte status;

    // getters & setters

	public Warehouses() {
	}

	public Warehouses(Long id, Companies companies, Set<GoodsReceipts> goodsReceiptses, Set<GoodsIssues> goodsIssueses,
			Set<Inventories> inventorieses, Set<InventoryLogs> inventoryLogses,
			Set<WarehouseLocations> warehouseLocationses, String code, String name, String address, Byte status) {
		super();
		this.id = id;
		this.companies = companies;
		this.goodsReceiptses = goodsReceiptses;
		this.goodsIssueses = goodsIssueses;
		this.inventorieses = inventorieses;
		this.inventoryLogses = inventoryLogses;
		this.warehouseLocationses = warehouseLocationses;
		this.code = code;
		this.name = name;
		this.address = address;
		this.status = status;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Set<GoodsReceipts> getGoodsReceiptses() {
		return goodsReceiptses;
	}

	public void setGoodsReceiptses(Set<GoodsReceipts> goodsReceiptses) {
		this.goodsReceiptses = goodsReceiptses;
	}

	public Set<GoodsIssues> getGoodsIssueses() {
		return goodsIssueses;
	}

	public void setGoodsIssueses(Set<GoodsIssues> goodsIssueses) {
		this.goodsIssueses = goodsIssueses;
	}

	public Set<Inventories> getInventorieses() {
		return inventorieses;
	}

	public void setInventorieses(Set<Inventories> inventorieses) {
		this.inventorieses = inventorieses;
	}

	public Set<InventoryLogs> getInventoryLogses() {
		return inventoryLogses;
	}

	public void setInventoryLogses(Set<InventoryLogs> inventoryLogses) {
		this.inventoryLogses = inventoryLogses;
	}

	public Set<WarehouseLocations> getWarehouseLocationses() {
		return warehouseLocationses;
	}

	public void setWarehouseLocationses(Set<WarehouseLocations> warehouseLocationses) {
		this.warehouseLocationses = warehouseLocationses;
	}

}
