package com.example.demo.entities;
// Generated 2 Jan 2026, 17:40:36 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * WarehouseLocations generated by hbm2java
 */
@Entity
@Table(name = "warehouse_locations")
public class WarehouseLocations {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /* =====================
       Relationships
       ===================== */

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "warehouse_id")
    private Warehouses warehouses;

    @OneToMany(mappedBy = "warehouseLocations", fetch = FetchType.LAZY)
    private Set<Inventories> inventorieses = new HashSet<>();

    /* =====================
       Columns
       ===================== */

    @Column(name = "location_code", length = 50)
    private String locationCode;

    @Column(name = "description", length = 255)
    private String description;

	public WarehouseLocations() {
	}

	public WarehouseLocations(Warehouses warehouses, String locationCode, String description, Set inventorieses) {
		this.warehouses = warehouses;
		this.locationCode = locationCode;
		this.description = description;
		this.inventorieses = inventorieses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Warehouses getWarehouses() {
		return this.warehouses;
	}

	public void setWarehouses(Warehouses warehouses) {
		this.warehouses = warehouses;
	}

	public String getLocationCode() {
		return this.locationCode;
	}

	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getInventorieses() {
		return this.inventorieses;
	}

	public void setInventorieses(Set inventorieses) {
		this.inventorieses = inventorieses;
	}

}
